'use client'

import { useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, ChevronRight, CreditCard, Fuel, History, KeyRound, Link2, MapPin, Plug, ReceiptText, RefreshCw, ShieldCheck, Trash2, TriangleAlert, Truck, Workflow, X } from 'lucide-react'

const capabilities=['vehicles','transactions','stations','trips']
const integrationSteps=[['Provider',Fuel],['Credentials',KeyRound],['Test',Plug],['Sync',History],['Matching',Workflow]] as const
const initialMatching=[
  ['Plate number','Provider plate number → Vehicle plate number','Best default for fuel card imports. Matches license plates with normalized spacing and casing.'],
  ['Internal ID','Provider internal fleet number → Vehicle internal ID','Use when the provider fleet number is the same identifier operators maintain on the vehicle.'],
  ['VIN','Provider VIN → Vehicle VIN','Matches the vehicle identification number when the provider sends it with the transaction.'],
  ['Serial number','Provider serial number → Vehicle serial number','Matches manufacturer or fleet serial numbers recorded on the vehicle.'],
  ['Call sign','Provider call sign → Vehicle call sign','Matches operational call signs when those are shared with the fuel provider.'],
  ['Fuel card number','Provider fuel card number → Vehicle fuel card number','Use when each vehicle has a dedicated fuel card number saved on the vehicle record.'],
  ['Trip number / order reference','Provider trip/order reference → Order public ID, internal ID, or tracking number','Links the transaction to an order when the provider sends a trip or order reference.'],
]

export function FuelProvidersPage(){
  const router=useRouter(),searchParams=useSearchParams()
  const initialStep=Math.min(5,Math.max(1,Number(searchParams.get('step'))||1))
  const [setup,setSetup]=useState(()=>searchParams.get('setup')==='new'),[step,setStep]=useState(initialStep),[token,setToken]=useState(''),[tested,setTested]=useState(false)
  const [name,setName]=useState('PetroApp'),[days,setDays]=useState('7'),[reports,setReports]=useState(true),[connected,setConnected]=useState(false)
  const [matching,setMatching]=useState(initialMatching),[notice,setNotice]=useState('')
  const metrics=useMemo(()=>[
    {label:'Connected integrations',value:connected?'1':'0',detail:'Fuel card and fuel management accounts',action:'Connect integration',icon:Fuel},
    {label:'Last sync',value:'Not synced',detail:'Most recent completed import',action:'Review sync',icon:History},
    {label:'Unmatched transactions',value:'0',detail:'No unmatched count',action:'Review matches',icon:TriangleAlert},
    {label:'Imported spend',value:'INR 0',detail:'0 L imported',action:'Open ledger',icon:ReceiptText},
  ],[connected])
  function goToStep(nextStep:number){const safeStep=Math.min(5,Math.max(1,nextStep));setStep(safeStep);router.replace(`/integrations?view=fuel-Integrations&setup=new&step=${safeStep}`,{scroll:false})}
  function begin(){setSetup(true);setStep(1);setNotice('');router.push('/integrations?view=fuel-Integrations&setup=new&step=1')}
  function cancel(){setSetup(false);setStep(1);router.push('/integrations?view=fuel-Integrations')}
  function move(index:number,direction:number){setMatching(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next})}
  function testConnection(){if(!token.trim()){setNotice('Enter the PetroApp API Token before testing the connection.');setTested(false);return}setTested(true);setNotice('PetroApp connection test completed successfully.')}
  function finish(){if(!token.trim()){goToStep(2);setNotice('API Token is required before creating the integration.');return}setConnected(true);setSetup(false);setNotice('PetroApp connected successfully. Fuel transactions are ready to sync.');router.push('/integrations?view=fuel-Integrations')}

  if(setup)return <main className="telematics-setup fuel-setup"><header><div><span>Fuel integration setup</span><h1>Connect Fuel Integration</h1><p>Connect PetroApp or another fuel card/fuel management system, test credentials, and configure transaction imports.</p></div><button className="secondary" onClick={cancel}><X/>Cancel</button></header><nav aria-label="Fuel integration steps">{integrationSteps.map(([label,Icon],index)=><button key={label} className={step===index+1?'active':step>index+1?'done':''} onClick={()=>goToStep(index+1)}><b>{step>index+1?<Check/>:<Icon/>}</b><span><small>{index+1}</small><strong>{label}</strong></span></button>)}</nav><section className="telematics-form fuel-form"><div className="telematics-fields">
    {step===1&&<><h2>Choose Fuel Integration</h2><p>Select the system to connect for fuel card bills, purchase transactions, station locations, or vehicle fuel identifiers.</p><ProviderCard selected/></>}
    {step===2&&<><h2>Credentials</h2><p>These credentials are stored on the connection and used to test and import provider transactions.</p><label>API Token*<input aria-label="API Token" autoFocus value={token} onChange={e=>setToken(e.target.value)} placeholder="API Token"/></label></>}
    {step===3&&<><h2>Test Connection</h2><p>Confirm the provider accepts the credentials before saving this fuel integration.</p><div className={`fuel-test ${tested?'success':''}`}><ShieldCheck/><span><strong>{tested?'Connection successful':'Ready to test'}</strong><small>{tested?'PetroApp accepted the supplied credentials.':'Run a live credential test before saving so operators know the integration can import fuel data.'}</small></span></div><div className="fuel-test-actions"><button className="primary" onClick={testConnection}>Test Connection</button><button className="secondary" onClick={()=>setNotice(token.trim()?'Diagnostics: credentials are formatted and the provider endpoint is available.':'Diagnostics: API Token is missing. Add credentials before testing.')}>Show diagnostics</button></div></>}
    {step===4&&<><h2>Sync Settings</h2><p>Choose how fuel transactions are imported from this system.</p><label>Integration name<input aria-label="Integration name" value={name} onChange={e=>setName(e.target.value)}/></label><label>Default sync window<input aria-label="Default sync window" type="number" min="1" value={days} onChange={e=>setDays(e.target.value)}/></label><label className="fuel-check"><input type="checkbox" checked={reports} onChange={e=>setReports(e.target.checked)}/>Create Fuel Reports after vehicle match</label><p>Provider bills remain in Fuel Transactions. Fuel Reports are created only when a transaction is matched to a vehicle.</p></>}
    {step===5&&<><h2>Vehicle Matching Priority</h2><p>Choose which provider identifiers should be used for automatic matching and put the most reliable identifier first.</p><div className="matching-help"><strong>How matching works</strong><p>Fuel transactions arrive with vehicle identifiers from the provider. Matching checks this list from top to bottom and links the transaction to the first vehicle or order found.</p></div><div className="matching-title"><h3>Priority list</h3><span>{matching.length} active</span></div><div className="matching-list">{matching.map((item,index)=><article key={item[0]}><b>Priority {index+1}</b><div><strong>{item[0]}</strong><small>{item[1]}</small><p>{item[2]}</p></div><aside><button aria-label={`Move ${item[0]} earlier`} disabled={!index} onClick={()=>move(index,-1)}><ArrowUp/></button><button aria-label={`Move ${item[0]} later`} disabled={index===matching.length-1} onClick={()=>move(index,1)}><ArrowDown/></button><button aria-label={`Remove ${item[0]}`} onClick={()=>setMatching(list=>list.filter((_,i)=>i!==index))}><Trash2/></button></aside></article>)}</div><h3>Available identifiers</h3><button className="available-id" onClick={()=>!matching.some(i=>i[0]==='Provider vehicle ID')&&setMatching(list=>[...list,['Provider vehicle ID','Provider-specific vehicle ID → Vehicle provider metadata','Matches provider-specific vehicle metadata.']])}><Truck/><span><strong>Provider vehicle ID</strong><small>Provider-specific vehicle ID → Vehicle provider metadata</small></span></button></>}
  </div>{step<5&&<aside><strong>PetroApp</strong><p>PetroApp fuel card bills, vehicles, trips, and station locations.</p><div>{capabilities.map(capability=><span key={capability}>{capability}</span>)}</div></aside>}</section><footer><p>After saving, run a sync to import provider bills into Fuel Transactions.</p><div><button className="secondary" onClick={cancel}>Cancel</button><button className="secondary" disabled={step===1} onClick={()=>goToStep(step-1)}><ArrowLeft/>Back</button>{step<5?<button className="primary" disabled={step===2&&!token.trim()} onClick={()=>goToStep(step+1)}>Next<ChevronRight/></button>:<button className="primary" onClick={finish}><Check/>Create Integration</button>}</div></footer>{notice&&<div className="telematics-notice">{notice}<button onClick={()=>setNotice('')}><X/></button></div>}</main>

  return <main className="telematics-hub fuel-hub"><header><div><h1>Fuel Integrations</h1><span>0 sync issues</span><p>Connect fuel card providers or fuel management systems, import provider bills as fuel transactions, match them to vehicles and trips, then create linked fuel reports for operations.</p></div><div><button className="icon-button" aria-label="Reload" onClick={()=>setNotice('Fuel integration status refreshed.')}><RefreshCw/></button><button className="primary" onClick={begin}><Fuel/>Connect Integration</button></div></header>{notice&&<div className="telematics-notice" role="status"><Check/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X/></button></div>}<section className="telematics-metrics fuel-metrics">{metrics.map((metric,index)=><article className={`fuel-metric fuel-metric-${index+1}`} key={metric.label}><header><span>{metric.label}</span><b><metric.icon/></b></header><strong>{metric.value}</strong><footer><p title={metric.detail}>{metric.detail}</p>{metric.label==='Connected integrations'||metric.label==='Last sync'?<button onClick={begin}>{metric.action}<ArrowRight/></button>:<a href="/fuel-transactions">{metric.action}<ArrowRight/></a>}</footer></article>)}</section>{!connected&&<section className="fuel-empty"><Fuel/><h2>No fuel integrations connected yet</h2><p>Start by connecting PetroApp or another fuel card/fuel management system. Provider bills import into Fuel Transactions, match to vehicles and trips, and create linked Fuel Reports once matched.</p><button className="primary" onClick={begin}><Link2/>Connect Integration</button></section>}<section className="native-providers fuel-providers"><header><h2>Available Fuel Integrations</h2><p>Connect providers that supply fuel card bills, purchase transactions, vehicle identifiers, station locations, or trip references.</p></header><div><button onClick={begin}><ProviderCard selected={connected}/><footer>{connected?'Manage integration':'Connect integration'}<ChevronRight/></footer></button></div></section></main>
}

function ProviderCard({selected=false}:{selected?:boolean}){return <div className="fuel-provider-card"><header><span className="provider-logo"><CreditCard/></span><span><strong>PetroApp</strong><small>Fuel card integration</small></span><em>{selected?'Selected':'Available'}</em></header><p>PetroApp fuel card bills, vehicles, trips, and station locations.</p><div>{capabilities.map(capability=><span key={capability}>{capability==='stations'?<MapPin/>:capability==='transactions'?<Fuel/>:<Truck/>}{capability}</span>)}</div></div>}
