'use client'

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, ArrowUpRight, Check, ChevronLeft, ChevronRight, Eye, Funnel, MoreHorizontal, Plus, RefreshCw, Search, SlidersHorizontal, Trash2, Upload, X } from 'lucide-react'
import { maintenanceApi, type MaintenanceRecord as ApiRecord } from '@/lib/maintenance-api'
import { fetchAuthenticated } from '@/hooks/use-api-data'

type LineItem = { id: string; description: string; quantity: string; unitCost: string }
type AssetOption = { id: string; label: string; type: 'Vehicle' | 'Equipment' }
type WorkOrderOption = { id: string; label: string; vehicleId?: string; equipmentId?: string }
type Maintenance = { id: string; summary: string; asset: string; assetType: string; performer: string; performerType: string; workOrder: string; type: string; status: string; priority: string; scheduledAt: string; startedAt: string; completedAt: string; odometer: string; engineHours: string; currency: string; labourCost: string; tax: string; lineItems: LineItem[]; notes: string; metadata: Record<string, string>; created: string; updated: string }
const columns = ['Summary', 'Asset', 'Performed By', 'Type', 'Status', 'Priority', 'Scheduled At', 'Total Cost', 'Created'] as const
type Column = (typeof columns)[number]
const empty = (): Maintenance => ({ id: '', summary: '', asset: '', assetType: '', performer: '', performerType: '', workOrder: '', type: '', status: '', priority: '', scheduledAt: '', startedAt: '', completedAt: '', odometer: '', engineHours: '', currency: 'INR', labourCost: '', tax: '', lineItems: [], notes: '', metadata: {}, created: '', updated: '' })
const emptyFilters = () => ({ summary: '', type: '', status: '', priority: '', scheduledAt: '', created: '', updated: '' })
const total = (row: Maintenance) => Number(row.labourCost || 0) + Number(row.tax || 0) + row.lineItems.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitCost || 0), 0)
const money = (amount: number, currency: string) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: currency || 'INR' }).format(amount)
const fromApi = (row: ApiRecord): Maintenance => ({ ...empty(), id: row.id, summary: row.summary, asset: row.vehicle_id || row.equipment_id || '', assetType: row.vehicle_id ? 'Vehicle' : 'Equipment', workOrder: row.work_order_id, type: row.maintenance_type, status: 'Completed', priority: 'Medium', scheduledAt: row.performed_at, startedAt: row.performed_at, completedAt: row.performed_at, odometer: String(row.odometer_km || ''), engineHours: String(row.engine_hours || ''), currency: row.currency, labourCost: String(row.actual_cost_minor / 100), notes: row.summary, created: row.created_at, updated: row.created_at })

export function MaintenanceMaintenancesPage() {
  const [rows, setRows] = useState<Maintenance[]>([]), [loading, setLoading] = useState(true), [search, setSearch] = useState('')
  const [filtersOpen, setFiltersOpen] = useState(false), [columnsOpen, setColumnsOpen] = useState(false)
  const [filters, setFilters] = useState(emptyFilters), [draftFilters, setDraftFilters] = useState(emptyFilters)
  const [visibleColumns, setVisibleColumns] = useState<Record<Column, boolean>>(() => Object.fromEntries(columns.map(column => [column, true])) as Record<Column, boolean>)
  const [selected, setSelected] = useState<string[]>([]), [menu, setMenu] = useState<string | null>(null)
  const [editor, setEditor] = useState<Maintenance | null>(null), [viewOnly, setViewOnly] = useState(false), [deleting, setDeleting] = useState<Maintenance | null>(null), [notice, setNotice] = useState('')
  const [assets, setAssets] = useState<AssetOption[]>([])
  const [workOrders, setWorkOrders] = useState<WorkOrderOption[]>([])
  const fileRef = useRef<HTMLInputElement>(null)
  const load = async () => { try { setRows((await maintenanceApi.listRecords()).map(fromApi)) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to load maintenances.') } finally { setLoading(false) } }
  const loadAssets = async () => { try { const [equipment, vehicleResponse, workOrderRows] = await Promise.all([maintenanceApi.listEquipment(), fetchAuthenticated('/v1/admin/vehicles'), maintenanceApi.listWorkOrders()]); const body = vehicleResponse.ok ? await vehicleResponse.json() as { data?: Array<Record<string, unknown>> } | Array<Record<string, unknown>> : []; const vehicles = Array.isArray(body) ? body : body.data || []; setAssets([...vehicles.map(row => ({ id: String(row.id || ''), label: String(row.name || row.call_sign || row.plate_number || row.id || ''), type: 'Vehicle' as const })).filter(row => row.id), ...equipment.map(row => ({ id: row.id, label: `${row.name}${row.code ? ` (${row.code})` : ''}`, type: 'Equipment' as const }))]); setWorkOrders(workOrderRows.filter(row => row.status !== 'completed' && row.status !== 'cancelled').map(row => ({ id: row.id, label: `${row.code} — ${row.subject}`, vehicleId: row.vehicle_id, equipmentId: row.equipment_id }))) } catch { setAssets([]); setWorkOrders([]) } }
  useEffect(() => { const timer = window.setTimeout(() => { void load(); void loadAssets() }, 0); return () => window.clearTimeout(timer) }, [])
  const visible = useMemo(() => rows.filter(row => `${row.summary} ${row.asset} ${row.performer} ${row.type} ${row.status} ${row.priority}`.toLowerCase().includes(search.toLowerCase()) && row.summary.toLowerCase().includes(filters.summary.toLowerCase()) && row.type.toLowerCase().includes(filters.type.toLowerCase()) && row.status.toLowerCase().includes(filters.status.toLowerCase()) && row.priority.toLowerCase().includes(filters.priority.toLowerCase()) && row.scheduledAt.includes(filters.scheduledAt) && row.created.includes(filters.created) && row.updated.includes(filters.updated)), [rows, search, filters])
  const save = async (event: FormEvent) => { event.preventDefault(); if (!editor?.summary || !editor.type || !editor.priority || !editor.assetType || !editor.asset) { setNotice('Complete the required fields and select a vehicle or equipment item.'); return } if (editor.id) { setNotice('Completed maintenance records are immutable and cannot be edited.'); return } const category = editor.type.toLowerCase().startsWith('preventive') ? 'preventive' : editor.type.toLowerCase(); const actualCostMinor = Math.round(total(editor) * 100); try { let workOrder = editor.workOrder ? (await maintenanceApi.listWorkOrders()).find(row => row.id === editor.workOrder) : undefined; if (!workOrder) workOrder = await maintenanceApi.createWorkOrder({ subject: editor.summary, description: editor.notes || undefined, category, priority: editor.priority.toLowerCase(), [editor.assetType === 'Vehicle' ? 'vehicle_id' : 'equipment_id']: editor.asset, currency: editor.currency, estimated_cost_minor: actualCostMinor, instructions: editor.notes || undefined }); let allowed = await maintenanceApi.allowedActions(workOrder.id); if (allowed.actions.includes('open')) { workOrder = await maintenanceApi.transitionWorkOrder(workOrder.id, { action: 'open' }); allowed = await maintenanceApi.allowedActions(workOrder.id) } if (allowed.actions.includes('start')) { workOrder = await maintenanceApi.transitionWorkOrder(workOrder.id, { action: 'start' }); allowed = await maintenanceApi.allowedActions(workOrder.id) } if (!allowed.actions.includes('complete')) throw new Error('The linked work order cannot be completed from its current status.'); await maintenanceApi.transitionWorkOrder(workOrder.id, { action: 'complete', actual_cost_minor: actualCostMinor, ...(editor.odometer ? { odometer_km: Number(editor.odometer) } : {}), ...(editor.engineHours ? { engine_hours: Number(editor.engineHours) } : {}) }); await load(); setEditor(null); setNotice('Maintenance created and added to service history.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to create maintenance.') } }
  const remove = async () => { if (!deleting) return; setDeleting(null); setNotice('Completed maintenance records are immutable and cannot be deleted.') }
  const exportRows = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(rows, null, 2)], { type: 'application/json' })), link = document.createElement('a'); link.href = url; link.download = 'maintenances.json'; link.click(); URL.revokeObjectURL(url) }
  const importRows = async (file?: File) => { if (!file) return; setNotice('Maintenance history cannot be imported directly. Complete work orders to create verified service records.') }
  return <div className="maintenance-list-page maintenances-page">
    <header className="maintenance-list-header"><h2>Maintenances</h2><div className="maintenance-list-search"><Search /><input aria-label="Search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search Maintenances" /></div><div className="maintenance-list-actions">
      <button aria-label="Filter maintenances" className={filtersOpen ? 'active' : ''} onClick={() => { setDraftFilters(filters); setFiltersOpen(value => !value); setColumnsOpen(false) }}><Funnel /></button><button aria-label="Customize columns" className={columnsOpen ? 'active' : ''} onClick={() => { setColumnsOpen(value => !value); setFiltersOpen(false) }}><SlidersHorizontal /></button><button aria-label="Refresh" onClick={() => { setLoading(true); void load() }}><RefreshCw className={loading ? 'spin' : ''} /></button><button className="new-schedule-action" onClick={() => { setViewOnly(false); setEditor(empty()) }}><Plus />New</button><button className="import-schedules-action" onClick={() => fileRef.current?.click()}><Upload />Import</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={event => void importRows(event.target.files?.[0])} /><button className="export-schedules-action" onClick={exportRows}><ArrowUpRight />Export</button>
      {filtersOpen && <div className="maintenance-filter-panel maintenance-record-filter"><header>Filters</header><div className="maintenance-filter-grid">{Object.entries(draftFilters).map(([key, value]) => <FilterInput key={key} label={{ summary: 'Summary', type: 'Type', status: 'Status', priority: 'Priority', scheduledAt: 'Scheduled At', created: 'Created', updated: 'Updated' }[key] || key} value={value} onChange={next => setDraftFilters(current => ({ ...current, [key]: next }))} />)}</div><footer><button type="button" onClick={() => { const cleared = emptyFilters(); setDraftFilters(cleared); setFilters(cleared); setFiltersOpen(false) }}><Trash2 />Clear</button><button type="button" className="apply" onClick={() => { setFilters(draftFilters); setFiltersOpen(false) }}><Check />Apply</button></footer></div>}
      {columnsOpen && <div className="maintenance-columns-menu"><strong>Customize columns</strong>{columns.map(column => <label key={column}><input type="checkbox" checked={visibleColumns[column]} onChange={event => setVisibleColumns(current => ({ ...current, [column]: event.target.checked }))} />{column}</label>)}<button className="columns-done" onClick={() => setColumnsOpen(false)}>Done</button></div>}
    </div></header>{notice && <div className="maintenance-list-notice">{notice}<button aria-label="Dismiss message" onClick={() => setNotice('')}><X /></button></div>}
    <section className="maintenance-table-panel"><div className="table-wrap"><table className="maintenance-schedules-table maintenances-table"><thead><tr><th><input aria-label="Select all maintenances" type="checkbox" checked={visible.length > 0 && selected.length === visible.length} onChange={event => setSelected(event.target.checked ? visible.map(row => row.id) : [])} /></th>{columns.filter(column => visibleColumns[column]).map(column => <th key={column}>{column}<span>↕</span></th>)}<th /></tr></thead><tbody>{visible.map(row => <tr key={row.id}><td><input aria-label={`Select ${row.summary}`} type="checkbox" checked={selected.includes(row.id)} onChange={event => setSelected(items => event.target.checked ? [...items, row.id] : items.filter(id => id !== row.id))} /></td>{visibleColumns.Summary && <td><button className="schedule-id" onClick={() => { setViewOnly(true); setEditor(row) }}>{row.summary}</button></td>}{visibleColumns.Asset && <td>{row.asset || '—'}</td>}{visibleColumns['Performed By'] && <td>{row.performer || '—'}</td>}{visibleColumns.Type && <td><span className="schedule-type">{row.type}</span></td>}{visibleColumns.Status && <td><span className={`schedule-status ${row.status.toLowerCase().replace(' ', '-')}`}>{row.status}</span></td>}{visibleColumns.Priority && <td>{row.priority}</td>}{visibleColumns['Scheduled At'] && <td>{row.scheduledAt || '—'}</td>}{visibleColumns['Total Cost'] && <td>{money(total(row), row.currency)}</td>}{visibleColumns.Created && <td>{row.created ? new Date(row.created).toLocaleString() : '—'}</td>}<td className="schedule-row-actions"><button aria-label={`Actions for ${row.summary}`} onClick={() => setMenu(menu === row.id ? null : row.id)}><MoreHorizontal /></button>{menu === row.id && <div role="menu"><strong>Maintenance Actions</strong><button role="menuitem" onClick={() => { setViewOnly(true); setEditor(row); setMenu(null) }}>View Maintenance</button><button role="menuitem" onClick={() => { setViewOnly(false); setEditor(row); setMenu(null) }}>Edit Maintenance</button><button role="menuitem" className="danger" onClick={() => { setDeleting(row); setMenu(null) }}>Delete Maintenance</button></div>}</td></tr>)}</tbody></table></div>{!loading && !visible.length && <div className="work-orders-empty"><span><AlertTriangle /></span><h3>No maintenances yet</h3><p>Create maintenance records to preserve service history, costs, and asset readings.</p><div><button className="primary" onClick={() => setEditor(empty())}><Plus />New maintenance</button></div></div>}<footer><p>Showing <b>{visible.length ? 1 : 0}</b> to <b>{visible.length}</b> of <b>{visible.length}</b> results</p><div><button disabled><ChevronLeft /></button><button className="active">1</button><button disabled><ChevronRight /></button></div></footer></section>
    {editor && <MaintenanceEditor value={editor} assets={assets} workOrders={workOrders} viewOnly={viewOnly} onChange={setEditor} onClose={() => setEditor(null)} onSave={save} />}
    {deleting && <div className="vehicle-delete-backdrop" onMouseDown={event => event.target === event.currentTarget && setDeleting(null)}><section className="vehicle-delete-dialog" role="alertdialog" aria-modal="true"><div className="vehicle-delete-content"><span className="vehicle-delete-warning"><AlertTriangle /></span><div><h2>Delete Maintenance?</h2><p>This action cannot be undone. The maintenance record will be permanently removed.</p></div></div><footer><button onClick={() => setDeleting(null)}><X />Cancel</button><button className="danger" onClick={() => void remove()}><Trash2 />Confirm Delete</button></footer></section></div>}
  </div>
}

function MaintenanceEditor({ value, assets, workOrders, viewOnly, onChange, onClose, onSave }: { value: Maintenance; assets: AssetOption[]; workOrders: WorkOrderOption[]; viewOnly: boolean; onChange: (value: Maintenance) => void; onClose: () => void; onSave: (event: FormEvent) => void }) {
  const update = <K extends keyof Maintenance>(key: K, next: Maintenance[K]) => onChange({ ...value, [key]: next }), updateLine = (id: string, changes: Partial<LineItem>) => update('lineItems', value.lineItems.map(item => item.id === id ? { ...item, ...changes } : item)), parts = value.lineItems.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unitCost || 0), 0)
  return <div className="schedule-editor-backdrop"><section className="schedule-editor maintenance-editor reference-maintenance-editor work-order-reference-editor" role="dialog" aria-modal="true" aria-label={viewOnly ? 'Maintenance details' : value.id ? 'Edit maintenance' : 'Create new maintenance'}><form onSubmit={onSave}><header><div><h2>{viewOnly ? value.summary : value.id ? 'Edit maintenance' : 'Create new maintenance'}</h2><p>{viewOnly ? 'Review maintenance details.' : 'Record service activity, costs, and readings.'}</p></div><div>{!viewOnly && <button className="primary" type="submit">{value.id ? 'Save Changes' : 'Create Maintenance'}</button>}<button type="button" aria-label="Close maintenance form" onClick={onClose}><X /></button></div></header><div className="schedule-editor-body">
    <Section title="Identification" subtitle="Maintenance Details"><label className="wide">Summary<input disabled={viewOnly} required value={value.summary} onChange={event => update('summary', event.target.value)} placeholder="Brief summary of the maintenance activity" /></label><div className="maintenance-classification wide"><strong>Type, Status &amp; Priority</strong><div><label>Type<select disabled={viewOnly} required value={value.type} onChange={event => update('type', event.target.value)}><option value="">Select Maintenance Type</option><option>Inspection</option><option>Service</option><option>Repair</option><option>Preventive Maintenance</option></select></label><label>Status<select disabled={viewOnly} required value={value.status} onChange={event => update('status', event.target.value)}><option value="">Select Status</option><option>Scheduled</option><option>In Progress</option><option>Completed</option><option>Cancelled</option></select></label><label>Priority<select disabled={viewOnly} required value={value.priority} onChange={event => update('priority', event.target.value)}><option value="">Select Priority</option><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></label></div></div></Section>
    <Section title="Asset & Work Order" subtitle="Maintainable Asset"><label>Asset Type<select disabled={viewOnly} required value={value.assetType} onChange={event => onChange({ ...value, assetType: event.target.value, asset: '', workOrder: '' })}><option value="">Select asset type (Vehicle, Equipment…)</option><option>Vehicle</option><option>Equipment</option></select></label>{value.assetType && <label>Asset<select disabled={viewOnly} required value={value.asset} onChange={event => update('asset', event.target.value)}><option value="">Select asset</option>{assets.filter(asset => asset.type === value.assetType).map(asset => <option key={asset.id} value={asset.id}>{asset.label}</option>)}</select></label>}<label>Performed By Type<select disabled={viewOnly} value={value.performerType} onChange={event => update('performerType', event.target.value)}><option value="">Select performer type (Vendor, Driver, Contact…)</option><option>Vendor</option><option>Driver</option><option>Contact</option></select></label>{value.performerType && <label>Performed By<input disabled={viewOnly} value={value.performer} onChange={event => update('performer', event.target.value)} placeholder="Select or enter performer" /></label>}<label className="wide">Work Order<select disabled={viewOnly} value={value.workOrder} onChange={event => { const id = event.target.value; const selected = workOrders.find(row => row.id === id); onChange({ ...value, workOrder: id, ...(selected?.vehicleId ? { assetType: 'Vehicle', asset: selected.vehicleId } : selected?.equipmentId ? { assetType: 'Equipment', asset: selected.equipmentId } : {}) }) }}><option value="">Link to a Work Order (optional)</option>{workOrders.map(row => <option key={row.id} value={row.id}>{row.label}</option>)}</select></label></Section>
    <Section title="Scheduling & Readings" subtitle="Dates"><label>Scheduled At<input disabled={viewOnly} type="datetime-local" value={value.scheduledAt} onChange={event => update('scheduledAt', event.target.value)} /></label><label>Started At<input disabled={viewOnly} type="datetime-local" value={value.startedAt} onChange={event => update('startedAt', event.target.value)} /></label><label>Completed At<input disabled={viewOnly} type="datetime-local" value={value.completedAt} onChange={event => update('completedAt', event.target.value)} /></label><label>Odometer (km)<input disabled={viewOnly} type="number" min="0" value={value.odometer} onChange={event => update('odometer', event.target.value)} /></label><label>Engine Hours<input disabled={viewOnly} type="number" min="0" value={value.engineHours} onChange={event => update('engineHours', event.target.value)} /></label></Section>
    <Section title="Costs"><label>Currency<select disabled={viewOnly} value={value.currency} onChange={event => update('currency', event.target.value)}><option>INR</option><option>USD</option><option>SGD</option><option>EUR</option></select></label><label>Labour Cost<input disabled={viewOnly} type="number" min="0" step="0.01" value={value.labourCost} onChange={event => update('labourCost', event.target.value)} placeholder="0.00" /></label><label>Tax<input disabled={viewOnly} type="number" min="0" step="0.01" value={value.tax} onChange={event => update('tax', event.target.value)} placeholder="0.00" /></label><div className="maintenance-line-items wide"><strong>Parts & Services</strong>{value.lineItems.map(item => <div key={item.id}><input disabled={viewOnly} aria-label="Line item description" value={item.description} onChange={event => updateLine(item.id, { description: event.target.value })} placeholder="Description" /><input disabled={viewOnly} aria-label="Line item quantity" type="number" min="0" value={item.quantity} onChange={event => updateLine(item.id, { quantity: event.target.value })} placeholder="Qty" /><input disabled={viewOnly} aria-label="Line item unit cost" type="number" min="0" step="0.01" value={item.unitCost} onChange={event => updateLine(item.id, { unitCost: event.target.value })} placeholder="Unit cost" />{!viewOnly && <button type="button" aria-label="Remove line item" onClick={() => update('lineItems', value.lineItems.filter(row => row.id !== item.id))}><Trash2 /></button>}</div>)}{!viewOnly && <button type="button" className="add-line" onClick={() => update('lineItems', [...value.lineItems, { id: crypto.randomUUID(), description: '', quantity: '1', unitCost: '' }])}><Plus />Add line item</button>}<dl><div><dt>Labour</dt><dd>{money(Number(value.labourCost || 0), value.currency)}</dd></div><div><dt>Parts</dt><dd>{money(parts, value.currency)}</dd></div><div><dt>Tax</dt><dd>{money(Number(value.tax || 0), value.currency)}</dd></div><div><dt>Total</dt><dd>{money(total(value), value.currency)}</dd></div></dl></div></Section>
    <Section title="Notes"><label className="wide">Notes<textarea disabled={viewOnly} value={value.notes} onChange={event => update('notes', event.target.value)} placeholder="Additional notes about this maintenance activity" /></label></Section><Section title="Metadata"><Metadata value={value.metadata} disabled={viewOnly} onChange={next => update('metadata', next)} /></Section>
  </div><footer><button type="button" onClick={onClose}>{viewOnly ? 'Close' : 'Cancel'}</button>{!viewOnly && <button className="primary" type="submit">{value.id ? 'Save Changes' : 'Create Maintenance'}</button>}</footer></form></section></div>
}

function Metadata({ value, disabled, onChange }: { value: Record<string, string>; disabled: boolean; onChange: (value: Record<string, string>) => void }) {
  const [filter, setFilter] = useState(''), [show, setShow] = useState(true), entries = Object.entries(value).filter(([key, item]) => `${key} ${item}`.toLowerCase().includes(filter.toLowerCase()))
  const rename = (oldKey: string, key: string) => { const next = { ...value }, item = next[oldKey]; delete next[oldKey]; next[key] = item; onChange(next) }
  return <div className="maintenance-metadata wide"><div><input aria-label="Filter metadata" placeholder="Filter keys..." value={filter} onChange={event => setFilter(event.target.value)} />{!disabled && <button type="button" onClick={() => onChange({ ...value, [`key_${Object.keys(value).length + 1}`]: '' })}><Plus />Add</button>}<button type="button" aria-label={show ? 'Hide metadata values' : 'Show metadata values'} onClick={() => setShow(current => !current)}><Eye /></button></div><section><header><strong>Key</strong><strong>Value</strong><span /></header>{entries.map(([key, item]) => <div key={key}><input disabled={disabled} aria-label="Metadata key" value={key} onChange={event => rename(key, event.target.value)} /><input disabled={disabled} aria-label={`Value for ${key}`} type={show ? 'text' : 'password'} value={item} onChange={event => onChange({ ...value, [key]: event.target.value })} />{!disabled && <button type="button" aria-label={`Remove ${key}`} onClick={() => { const next = { ...value }; delete next[key]; onChange(next) }}><Trash2 /></button>}</div>)}{!entries.length && <p>{Object.keys(value).length ? 'No metadata matches this filter.' : 'No metadata. Click Add to create one.'}</p>}</section></div>
}
function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <section><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}<div>{children}</div></section> }
function FilterInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><strong>{label}</strong><span><input aria-label={`Filter by ${label}`} placeholder={label} value={value} onChange={event => onChange(event.target.value)} />{value && <button type="button" aria-label={`Clear ${label} filter`} onClick={() => onChange('')}><X /></button>}</span></label> }
