'use client'

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, ArrowUpRight, Check, ChevronLeft, ChevronRight, ExternalLink, Eye, Funnel, ImagePlus, MoreHorizontal, Plus, RefreshCw, Search, SlidersHorizontal, Trash2, Upload, X } from 'lucide-react'
import { maintenanceApi, type MaintenanceEquipment as ApiEquipment } from '@/lib/maintenance-api'
import { ReferenceSelect, useMaintenanceReferenceOptions } from './use-maintenance-reference-options'

type Equipment = { id: string; name: string; code: string; type: string; status: string; serialNumber: string; manufacturer: string; model: string; assetType: string; assignedAsset: string; currency: string; purchasePrice: string; purchaseDate: string; warranty: string; image: string; metadata: Record<string, string>; created: string; updated: string }
const columns = ['Name', 'Code', 'Type', 'Status', 'Serial Number', 'Manufacturer', 'Created', 'Updated'] as const
type Column = (typeof columns)[number]
const empty = (): Equipment => ({ id: '', name: '', code: '', type: '', status: 'Available', serialNumber: '', manufacturer: '', model: '', assetType: '', assignedAsset: '', currency: 'INR', purchasePrice: '', purchaseDate: '', warranty: '', image: '', metadata: {}, created: '', updated: '' })
const emptyFilters = () => ({ name: '', code: '', type: '', status: '', created: '', updated: '' })
const fromApi = (row: ApiEquipment): Equipment => ({ ...empty(), id: row.id, name: row.name, code: row.code, type: row.type, status: row.status === 'out_of_service' ? 'Out of Service' : row.status === 'retired' ? 'Retired' : 'Available', serialNumber: row.serial_number || '', manufacturer: row.manufacturer || '', model: row.model || '', metadata: row.metadata || {}, created: row.created_at, updated: row.updated_at })

export function MaintenanceEquipmentPage() {
  const [rows, setRows] = useState<Equipment[]>([]), [loading, setLoading] = useState(true), [search, setSearch] = useState('')
  const [filters, setFilters] = useState(emptyFilters), [draftFilters, setDraftFilters] = useState(emptyFilters), [filtersOpen, setFiltersOpen] = useState(false), [columnsOpen, setColumnsOpen] = useState(false)
  const [visibleColumns, setVisibleColumns] = useState<Record<Column, boolean>>(() => Object.fromEntries(columns.map(column => [column, true])) as Record<Column, boolean>)
  const [selected, setSelected] = useState<string[]>([]), [menu, setMenu] = useState<string | null>(null), [editor, setEditor] = useState<Equipment | null>(null), [viewOnly, setViewOnly] = useState(false), [deleting, setDeleting] = useState<Equipment | null>(null), [guideOpen, setGuideOpen] = useState(false), [notice, setNotice] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  const load = async () => { try { setRows((await maintenanceApi.listEquipment()).map(fromApi)) } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to load equipment.') } finally { setLoading(false) } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer) }, [])
  const visible = useMemo(() => rows.filter(row => `${row.name} ${row.code} ${row.type} ${row.status} ${row.serialNumber} ${row.manufacturer}`.toLowerCase().includes(search.toLowerCase()) && row.name.toLowerCase().includes(filters.name.toLowerCase()) && row.code.toLowerCase().includes(filters.code.toLowerCase()) && row.type.toLowerCase().includes(filters.type.toLowerCase()) && row.status.toLowerCase().includes(filters.status.toLowerCase()) && row.created.includes(filters.created) && row.updated.includes(filters.updated)), [rows, search, filters])
  const save = async (event: FormEvent) => { event.preventDefault(); if (!editor?.name || !editor.type || !editor.status) { setNotice('Complete the required equipment fields.'); return } if (editor.id) { setNotice('Existing equipment is managed as a durable asset record.'); return } const metadata = { ...editor.metadata, ...(editor.assetType ? { assigned_asset_type: editor.assetType } : {}), ...(editor.assignedAsset ? { assigned_asset_id: editor.assignedAsset } : {}), ...(editor.purchasePrice ? { purchase_price: editor.purchasePrice } : {}), ...(editor.currency ? { purchase_currency: editor.currency } : {}), ...(editor.warranty ? { warranty: editor.warranty } : {}) }; try { await maintenanceApi.createEquipment({ name: editor.name, code: editor.code || undefined, type: editor.type, status: editor.status === 'Out of Service' || editor.status === 'Maintenance' ? 'out_of_service' : editor.status === 'Retired' ? 'retired' : 'active', serial_number: editor.serialNumber || undefined, manufacturer: editor.manufacturer || undefined, model: editor.model || undefined, metadata, ...(editor.purchaseDate ? { purchase_date: new Date(`${editor.purchaseDate}T00:00:00Z`).toISOString() } : {}) }); await load(); setEditor(null); setNotice('Equipment created.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Unable to save equipment.') } }
  const remove = async () => { if (!deleting) return; setDeleting(null); setNotice('Equipment cannot be deleted because maintenance history must retain its asset reference.') }
  const exportRows = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(rows, null, 2)], { type: 'application/json' })), link = document.createElement('a'); link.href = url; link.download = 'equipment.json'; link.click(); URL.revokeObjectURL(url) }
  const importRows = async (file?: File) => { if (!file) return; try { const values = JSON.parse(await file.text()) as Equipment[]; for (const value of values) await maintenanceApi.createEquipment({ name: value.name, code: value.code || undefined, type: value.type, status: value.status === 'Out of Service' || value.status === 'Maintenance' ? 'out_of_service' : 'active', serial_number: value.serialNumber || undefined, manufacturer: value.manufacturer || undefined, model: value.model || undefined, metadata: value.metadata || {} }); await load(); setNotice(`${values.length} equipment records imported.`) } catch { setNotice('Import failed. Check the equipment records.') } }
  return <div className="maintenance-list-page equipment-page"><header className="maintenance-list-header"><h2>Equipment</h2><div className="maintenance-list-search"><Search /><input aria-label="Search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search Equipment" /></div><div className="maintenance-list-actions">
    <button aria-label="Filter equipment" className={filtersOpen ? 'active' : ''} onClick={() => { setDraftFilters(filters); setFiltersOpen(value => !value); setColumnsOpen(false) }}><Funnel /></button><button aria-label="Customize columns" className={columnsOpen ? 'active' : ''} onClick={() => { setColumnsOpen(value => !value); setFiltersOpen(false) }}><SlidersHorizontal /></button><button aria-label="Refresh" onClick={() => { setLoading(true); void load() }}><RefreshCw className={loading ? 'spin' : ''} /></button><button className="new-schedule-action" onClick={() => { setViewOnly(false); setEditor(empty()) }}><Plus />New</button><button className="import-schedules-action" onClick={() => fileRef.current?.click()}><Upload />Import</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={event => void importRows(event.target.files?.[0])} /><button className="export-schedules-action" onClick={exportRows}><ArrowUpRight />Export</button>
    {filtersOpen && <div className="maintenance-filter-panel equipment-filter"><header>Filters</header><div className="maintenance-filter-grid">{Object.entries(draftFilters).map(([key, value]) => <FilterInput key={key} label={{ name: 'Name', code: 'Code', type: 'Type', status: 'Status', created: 'Created', updated: 'Updated' }[key] || key} value={value} onChange={next => setDraftFilters(current => ({ ...current, [key]: next }))} />)}</div><footer><button type="button" onClick={() => { const cleared = emptyFilters(); setDraftFilters(cleared); setFilters(cleared); setFiltersOpen(false) }}><Trash2 />Clear</button><button type="button" className="apply" onClick={() => { setFilters(draftFilters); setFiltersOpen(false) }}><Check />Apply</button></footer></div>}
    {columnsOpen && <div className="maintenance-columns-menu"><strong>Customize columns</strong>{columns.map(column => <label key={column}><input type="checkbox" checked={visibleColumns[column]} onChange={event => setVisibleColumns(current => ({ ...current, [column]: event.target.checked }))} />{column}</label>)}<button className="columns-done" onClick={() => setColumnsOpen(false)}>Done</button></div>}
  </div></header>{notice && <div className="maintenance-list-notice">{notice}<button aria-label="Dismiss message" onClick={() => setNotice('')}><X /></button></div>}
  <section className="maintenance-table-panel"><div className="table-wrap"><table className="maintenance-schedules-table equipment-table"><thead><tr><th><input aria-label="Select all equipment" type="checkbox" checked={visible.length > 0 && selected.length === visible.length} onChange={event => setSelected(event.target.checked ? visible.map(row => row.id) : [])} /></th>{columns.filter(column => visibleColumns[column]).map(column => <th key={column}>{column}<span>↕</span></th>)}<th /></tr></thead><tbody>{visible.map(row => <tr key={row.id}><td><input aria-label={`Select ${row.name}`} type="checkbox" checked={selected.includes(row.id)} onChange={event => setSelected(items => event.target.checked ? [...items, row.id] : items.filter(id => id !== row.id))} /></td>{visibleColumns.Name && <td><button className="schedule-id" onClick={() => { setViewOnly(true); setEditor(row) }}>{row.name}</button></td>}{visibleColumns.Code && <td>{row.code}</td>}{visibleColumns.Type && <td><span className="schedule-type">{row.type}</span></td>}{visibleColumns.Status && <td><span className={`schedule-status ${row.status.toLowerCase()}`}>{row.status}</span></td>}{visibleColumns['Serial Number'] && <td>{row.serialNumber || '—'}</td>}{visibleColumns.Manufacturer && <td>{row.manufacturer || '—'}</td>}{visibleColumns.Created && <td>{row.created ? new Date(row.created).toLocaleString() : '—'}</td>}{visibleColumns.Updated && <td>{row.updated ? new Date(row.updated).toLocaleString() : '—'}</td>}<td className="schedule-row-actions"><button aria-label={`Actions for ${row.name}`} onClick={() => setMenu(menu === row.id ? null : row.id)}><MoreHorizontal /></button>{menu === row.id && <div role="menu"><strong>Equipment Actions</strong><button role="menuitem" onClick={() => { setViewOnly(true); setEditor(row); setMenu(null) }}>View Equipment</button><button role="menuitem" onClick={() => { setViewOnly(false); setEditor(row); setMenu(null) }}>Edit Equipment</button><button role="menuitem" className="danger" onClick={() => { setDeleting(row); setMenu(null) }}>Delete Equipment</button></div>}</td></tr>)}</tbody></table></div>{!loading && !visible.length && <div className="work-orders-empty"><span><ImagePlus /></span><h3>Add your first equipment item</h3><p>Equipment records help track assigned assets, condition, service history, and operational readiness.</p><div><button onClick={() => fileRef.current?.click()}><Upload />Import</button><button className="primary" onClick={() => setEditor(empty())}><Plus />New equipment</button></div><button className="guide" onClick={() => setGuideOpen(true)}>Equipment guide</button></div>}<footer><p>Showing <b>{visible.length ? 1 : 0}</b> to <b>{visible.length || 1}</b> of <b>{visible.length}</b> results</p><div><button disabled><ChevronLeft /></button><button className="active">1</button><button disabled><ChevronRight /></button></div></footer></section>
  {editor && <EquipmentEditor value={editor} viewOnly={viewOnly} onChange={setEditor} onClose={() => setEditor(null)} onSave={save} />}
  {guideOpen && <div className="maintenance-guide-backdrop equipment-guide-backdrop" role="presentation" onMouseDown={event => event.target === event.currentTarget && setGuideOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="equipment-guide-title"><header><h2 id="equipment-guide-title">Equipment guide</h2><div><a href="/issues?view=equipment" target="_blank" aria-label="Open equipment guide in a new tab"><ExternalLink /></a><button aria-label="Close equipment guide" onClick={() => setGuideOpen(false)}><X /></button></div></header><div className="equipment-guide-brand"><span>D</span><strong>Droo Docs</strong><button type="button" aria-label="Toggle documentation theme">◐</button><button type="button" aria-label="Open documentation menu">☰</button></div><div className="equipment-guide-section"><span>◯</span><strong>Equipment</strong><b>⌄</b></div><article><span>Equipment</span><h1>Equipment</h1><p>Track operational assets beyond vehicles, including tools, trailers, containers, attachments, and powered equipment.</p><h2>What belongs in Equipment</h2><ul><li>Trailers and containers used for transport.</li><li>Attachments such as lifts, cranes, and refrigeration units.</li><li>Tools such as pallet jacks, scanners, and delivery trolleys.</li><li>Any asset with its own maintenance interval, repair history, or warranty.</li></ul><h2>Equipment details</h2><table><thead><tr><th>Field</th><th>Purpose</th></tr></thead><tbody><tr><td>Name and code</td><td>Human-readable and internal equipment identifiers.</td></tr><tr><td>Type and status</td><td>Classification and current operational availability.</td></tr><tr><td>Serial number</td><td>Manufacturer-issued asset identifier.</td></tr><tr><td>Assignment</td><td>Vehicle, location, or other asset currently using the equipment.</td></tr></tbody></table><h2>Creating equipment</h2><ol><li>Select <strong>New equipment</strong>.</li><li>Enter the identification and manufacturer details.</li><li>Choose its type, status, and current assignment.</li><li>Add purchase, warranty, and metadata information.</li><li>Select <strong>Create Equipment</strong>.</li></ol><h2>Maintenance workflow</h2><p>Equipment can participate in schedules, work orders, and maintenance history. Use those records to plan service, track repairs, and preserve asset readings and costs.</p><h2>Warranty tracking</h2><p>Record purchase and warranty information so teams can identify covered equipment before authorizing repair work.</p></article></section></div>}
  {deleting && <div className="vehicle-delete-backdrop" onMouseDown={event => event.target === event.currentTarget && setDeleting(null)}><section className="vehicle-delete-dialog" role="alertdialog" aria-modal="true"><div className="vehicle-delete-content"><span className="vehicle-delete-warning"><AlertTriangle /></span><div><h2>Delete Equipment?</h2><p>This action cannot be undone. The equipment record will be permanently removed.</p></div></div><footer><button onClick={() => setDeleting(null)}><X />Cancel</button><button className="danger" onClick={() => void remove()}><Trash2 />Confirm Delete</button></footer></section></div>}
  </div>
}

function EquipmentEditor({ value, viewOnly, onChange, onClose, onSave }: { value: Equipment; viewOnly: boolean; onChange: (value: Equipment) => void; onClose: () => void; onSave: (event: FormEvent) => void }) {
  const references = useMaintenanceReferenceOptions()
  const update = <K extends keyof Equipment>(key: K, next: Equipment[K]) => onChange({ ...value, [key]: next })
  const imageRef = useRef<HTMLInputElement>(null)
  const imageChanged = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => update('image', String(reader.result || '')); reader.readAsDataURL(file) }
  return <div className="schedule-editor-backdrop"><section className="schedule-editor equipment-editor work-order-reference-editor reference-equipment-editor" role="dialog" aria-modal="true" aria-label={viewOnly ? 'Equipment details' : value.id ? 'Edit equipment' : 'Create new equipment'}><form onSubmit={onSave}><header><div><h2>{viewOnly ? value.name : value.id ? 'Edit equipment' : 'Create new equipment'}</h2><p>{viewOnly ? 'Review equipment details.' : 'Add an operational equipment record.'}</p></div><div>{!viewOnly && <button className="primary" type="submit">{value.id ? 'Save Changes' : 'Create Equipment'}</button>}<button type="button" aria-label="Close equipment form" onClick={onClose}><X /></button></div></header><div className="schedule-editor-body">
    <Section title="Identification"><div className="equipment-image"><button type="button" disabled={viewOnly} onClick={() => imageRef.current?.click()}>{value.image ? <span style={{ backgroundImage: `url(${value.image})` }} /> : <ImagePlus />}<b>Upload Image</b><small>Supports JPG, PNG, GIF up to 10 MB</small></button><input ref={imageRef} hidden type="file" accept="image/jpeg,image/png,image/gif" onChange={event => imageChanged(event.target.files?.[0])} /></div><div className="equipment-details-grid wide"><strong>Equipment Details</strong><div><label>Name<input disabled={viewOnly} required value={value.name} onChange={event => update('name', event.target.value)} placeholder="Equipment name" /></label><label>Code<input disabled={viewOnly} value={value.code} onChange={event => update('code', event.target.value)} placeholder="Internal code or reference" /></label><label>Serial Number<input disabled={viewOnly} value={value.serialNumber} onChange={event => update('serialNumber', event.target.value)} placeholder="Manufacturer serial number" /></label><label>Manufacturer<input disabled={viewOnly} value={value.manufacturer} onChange={event => update('manufacturer', event.target.value)} placeholder="Manufacturer name" /></label><label>Model<input disabled={viewOnly} value={value.model} onChange={event => update('model', event.target.value)} placeholder="Model designation" /></label></div></div><div className="equipment-type-status wide"><strong>Type &amp; Status</strong><div><label>Type<select disabled={viewOnly} required value={value.type} onChange={event => update('type', event.target.value)}><option value="">Select Equipment Type</option><option>Tool</option><option>Machine</option><option>Trailer</option><option>Refrigeration Unit</option><option>Safety Equipment</option><option>Other</option></select></label><label>Status<select disabled={viewOnly} required value={value.status} onChange={event => update('status', event.target.value)}><option>Available</option><option>Assigned</option><option>Maintenance</option><option>Out of Service</option></select></label></div></div></Section>
    <Section title="Assignment" subtitle="Equipped To"><label>Asset Type<select disabled={viewOnly} value={value.assetType} onChange={event => onChange({ ...value, assetType: event.target.value, assignedAsset: '' })}><option value="">Select asset type</option><option>Vehicle</option><option>Equipment</option><option>Location</option></select></label>{value.assetType && <ReferenceSelect label="Assigned Asset" disabled={viewOnly} value={value.assignedAsset} options={references.assetsFor(value.assetType)} placeholder="Select assigned asset" onChange={assignedAsset => update('assignedAsset', assignedAsset)} />}</Section>
    <Section title="Purchase & Warranty" subtitle="Purchase Information"><label>Currency<select disabled={viewOnly} value={value.currency} onChange={event => update('currency', event.target.value)}><option>INR</option><option>USD</option><option>SGD</option><option>EUR</option></select></label><label>Purchase Price<input disabled={viewOnly} type="number" min="0" step="0.01" value={value.purchasePrice} onChange={event => update('purchasePrice', event.target.value)} placeholder="0.00" /></label><label>Purchase Date<input disabled={viewOnly} type="date" value={value.purchaseDate} onChange={event => update('purchaseDate', event.target.value)} /></label><label>Warranty<select disabled={viewOnly} value={value.warranty} onChange={event => update('warranty', event.target.value)}><option value="">Select Warranty (optional)</option><option>6 months</option><option>1 year</option><option>2 years</option><option>3 years</option><option>5 years</option></select></label></Section>
    <Section title="Metadata"><Metadata value={value.metadata} disabled={viewOnly} onChange={next => update('metadata', next)} /></Section>
  </div><footer><button type="button" onClick={onClose}>{viewOnly ? 'Close' : 'Cancel'}</button>{!viewOnly && <button className="primary" type="submit">{value.id ? 'Save Changes' : 'Create Equipment'}</button>}</footer></form></section></div>
}

function Metadata({ value, disabled, onChange }: { value: Record<string, string>; disabled: boolean; onChange: (value: Record<string, string>) => void }) { const [filter, setFilter] = useState(''), [show, setShow] = useState(true), entries = Object.entries(value).filter(([key, item]) => `${key} ${item}`.toLowerCase().includes(filter.toLowerCase())); const rename = (oldKey: string, key: string) => { const next = { ...value }, item = next[oldKey]; delete next[oldKey]; next[key] = item; onChange(next) }; return <div className="maintenance-metadata wide"><div><input aria-label="Filter metadata" placeholder="Filter keys..." value={filter} onChange={event => setFilter(event.target.value)} />{!disabled && <button type="button" onClick={() => onChange({ ...value, [`key_${Object.keys(value).length + 1}`]: '' })}><Plus />Add</button>}<button type="button" aria-label={show ? 'Hide metadata values' : 'Show metadata values'} onClick={() => setShow(current => !current)}><Eye /></button></div><section><header><strong>Key</strong><strong>Value</strong><span /></header>{entries.map(([key, item]) => <div key={key}><input disabled={disabled} aria-label="Metadata key" value={key} onChange={event => rename(key, event.target.value)} /><input disabled={disabled} aria-label={`Value for ${key}`} type={show ? 'text' : 'password'} value={item} onChange={event => onChange({ ...value, [key]: event.target.value })} />{!disabled && <button type="button" aria-label={`Remove ${key}`} onClick={() => { const next = { ...value }; delete next[key]; onChange(next) }}><Trash2 /></button>}</div>)}{!entries.length && <p>{Object.keys(value).length ? 'No metadata matches this filter.' : 'No metadata. Click Add to create one.'}</p>}</section></div> }
function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <section><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}<div>{children}</div></section> }
function FilterInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><strong>{label}</strong><span><input aria-label={`Filter by ${label}`} placeholder={label} value={value} onChange={event => onChange(event.target.value)} />{value && <button type="button" aria-label={`Clear ${label} filter`} onClick={() => onChange('')}><X /></button>}</span></label> }
