'use client'

import { useState } from 'react'
import { modules } from '@/lib/dashboard-config'
import { PageHeader } from '@/components/ui/page-header'

export function SettingsPage() {
  const [saved, setSaved] = useState(false), [name, setName] = useState('Droo Operations'), [timezone, setTimezone] = useState('Asia/Kolkata')
  return <><PageHeader config={modules['Organization Settings']} /><div className="settings-grid"><section className="panel settings-card"><header><div><h2>Organization profile</h2><p>Used in operational records and notifications.</p></div></header><div className="form-grid"><label><span>Organization name</span><input value={name} onChange={event => setName(event.target.value)} /></label><label><span>Timezone</span><select value={timezone} onChange={event => setTimezone(event.target.value)}><option>Asia/Kolkata</option><option>UTC</option><option>Asia/Dubai</option></select></label><label><span>Support email</span><input type="email" placeholder="operations@example.com" /></label><label><span>Default currency</span><select><option>INR — Indian Rupee</option><option>USD — US Dollar</option></select></label></div><div className="form-actions"><span>{saved ? 'Settings saved locally. Connect the organization API to persist them.' : ''}</span><button className="primary" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 3500) }}>Save changes</button></div></section><section className="panel settings-card"><header><div><h2>Access & security</h2><p>Tenant protection and session policy.</p></div></header><div className="setting-row"><div><strong>Multi-factor authentication</strong><span>Required for operations administrators</span></div><button className="toggle on" aria-label="Multi-factor authentication enabled"><i /></button></div><div className="setting-row"><div><strong>Signed webhook delivery</strong><span>Verify every outbound event using HMAC</span></div><button className="toggle on" aria-label="Signed webhooks enabled"><i /></button></div><div className="setting-row"><div><strong>Audit retention</strong><span>Keep immutable operational history</span></div><b>365 days</b></div></section></div></>
}
