'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { BookOpen, Boxes, CheckCircle2, CircleDollarSign, ExternalLink, Package, Plus, RefreshCw, Search, ShoppingBag, Store, UsersRound, X } from 'lucide-react'
import { fetchAuthenticated } from '@/hooks/use-api-data'

type Row = Record<string, unknown>
type View = 'dashboard'|'products'|'catalogs'|'customers'|'orders'|'networks'|'food-trucks'|'promotions'|'settings'|'launch'
const endpoint: Partial<Record<View,string>> = { products:'/v1/admin/storefront/products', catalogs:'/v1/admin/storefront/catalogs', customers:'/v1/admin/storefront/customers', orders:'/v1/admin/storefront/orders' }
const labels: Record<View,string> = {dashboard:'Storefront Dashboard',products:'Products',catalogs:'Catalogs',customers:'Customers',orders:'Orders',networks:'Networks','food-trucks':'Food Trucks',promotions:'Promotions',settings:'Storefront Settings',launch:'Launch App'}

function array(value: unknown): Row[] { if(Array.isArray(value))return value as Row[];if(value&&typeof value==='object'){const r=value as Row;const nested=r.data??r.products;return Array.isArray(nested)?nested as Row[]:[]}return [] }
function money(value: unknown,currency='INR'){return new Intl.NumberFormat('en-IN',{style:'currency',currency,maximumFractionDigits:2}).format(Number(value||0)/100)}
function date(value: unknown){if(typeof value!=='string')return '—';return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(value))}

export function StorefrontPage(){
  const params=useSearchParams(); const view=(params.get('view')||'dashboard') as View
  const [rows,setRows]=useState<Row[]>([]);const [metrics,setMetrics]=useState<Row>({});const [store,setStore]=useState<Row>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('');const [modal,setModal]=useState(false);const [revision,setRevision]=useState(0)
  const load=useCallback(async()=>{void revision;setLoading(true);setError('');try{const requests=[fetchAuthenticated('/v1/admin/storefront/store'),fetchAuthenticated('/v1/admin/storefront/metrics')];if(endpoint[view])requests.push(fetchAuthenticated(endpoint[view]!));const values=await Promise.all(requests);for(const response of values)if(!response.ok)throw new Error(`Storefront API returned ${response.status}`);setStore(await values[0].json());setMetrics(await values[1].json());setRows(values[2]?array(await values[2].json()):[])}catch(value){setError(value instanceof Error?value.message:'Unable to load Storefront');setRows([])}finally{setLoading(false)}},[view,revision])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
  const filtered=useMemo(()=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase())),[rows,search])
  const refresh=()=>setRevision(v=>v+1)
  return <section className="storefront-page">
    <header className="storefront-head"><div><small>COMMERCE</small><h1>{labels[view]||'Storefront'}</h1><p>{view==='dashboard'?'Monitor sales, orders, customers and your live product catalog.':`Manage your ${labels[view].toLowerCase()} from one workspace.`}</p></div><div><button className="secondary" onClick={refresh}><RefreshCw/> Refresh</button>{(view==='products'||view==='catalogs')&&<button className="primary" onClick={()=>setModal(true)}><Plus/> New {view==='products'?'product':'catalog'}</button>}</div></header>
    <div className="storefront-storebar"><span><Store/></span><p><small>ACTIVE STORE</small><strong>{String(store.name||'Droo Store')}</strong></p><em className="badge good"><i/>{String(store.status||'active')}</em><p><small>CURRENCY</small><strong>{String(store.currency||'INR')}</strong></p><p><small>PUBLIC CATALOG</small><strong>/storefront/v1/products</strong></p></div>
    {error&&<div className="storefront-error"><strong>Storefront is unavailable.</strong><span>{error}. Apply the Storefront migration and restart the Go API.</span></div>}
    {view==='dashboard'?<Dashboard metrics={metrics}/>:endpoint[view]?<ResourceTable view={view} rows={filtered} loading={loading} search={search} setSearch={setSearch}/>:<SupportingView view={view} store={store}/>} 
    {modal&&<Editor view={view} store={store} close={()=>setModal(false)} saved={()=>{setModal(false);refresh()}}/>}
  </section>
}

function Dashboard({metrics}:{metrics:Row}){const currency=String(metrics.currency||'INR');const cards=[['Revenue',money(metrics.revenue_minor,currency),CircleDollarSign],['Orders',String(metrics.orders||0),ShoppingBag],['Average order value',money(metrics.average_order_minor,currency),Boxes],['Active orders',String(metrics.active_orders||0),RefreshCw],['Completed orders',String(metrics.completed_orders||0),CheckCircle2],['Customers',String(metrics.customers||0),UsersRound],['Products',String(metrics.products||0),Package],['Cancellation rate',`${Number(metrics.cancellation_rate||0).toFixed(1)}%`,BookOpen]];return <><section className="storefront-kpis">{cards.map(([label,value,Icon])=><article key={String(label)}><span><Icon/></span><p><small>{String(label)}</small><strong>{String(value)}</strong><em>Current</em></p></article>)}</section><section className="storefront-dashboard-grid"><article><header><h2>Revenue trend</h2><p>Storefront revenue over the current period</p></header><div className="storefront-chart"><i/><i/><i/><i/><i/><i/><i/><svg viewBox="0 0 600 150" preserveAspectRatio="none"><polyline points="0,130 80,115 160,122 240,80 320,91 400,55 480,70 600,26"/></svg><span>Live completed orders populate this chart.</span></div></article><article><header><h2>Top products</h2><p>Products ranked by fulfilled quantity</p></header><div className="storefront-empty"><Package/><strong>{Number(metrics.products||0)} products available</strong><span>Sales ranking begins after checkout orders are completed.</span></div></article><article><header><h2>Orders by status</h2><p>Current storefront fulfillment health</p></header><div className="storefront-statuses">{[['Active',metrics.active_orders],['Completed',metrics.completed_orders],['All orders',metrics.orders]].map(([name,value])=><p key={String(name)}><span>{String(name)}</span><strong>{String(value||0)}</strong></p>)}</div></article><article><header><h2>Quick start</h2><p>Connect your commerce flow</p></header><ol className="storefront-steps"><li><b>1</b><span><strong>Create products</strong>Add inventory and pricing.</span></li><li><b>2</b><span><strong>Create an API key</strong>Use it server-side in the pharmacy app.</span></li><li><b>3</b><span><strong>Launch and checkout</strong>Orders enter Droo delivery operations.</span></li></ol></article></section></>}

function ResourceTable({view,rows,loading,search,setSearch}:{view:View;rows:Row[];loading:boolean;search:string;setSearch:(v:string)=>void}){const columns=view==='products'?['Name','SKU','Category','Price','Inventory','Status','Created']:view==='catalogs'?['Name','Products','Published','Created']:view==='customers'?['Customer','Email','Phone','Orders','Spent','Created']:['Reference','Status','Total','Delivery order','Created'];return <article className="storefront-table-card"><div className="storefront-tools"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${view}…`}/></label><span>{rows.length} records</span></div><div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={String(row.id)}>{view==='products'?<><td><strong>{String(row.name||'—')}</strong><small>{String(row.description||'')}</small></td><td><code>{String(row.sku||'—')}</code></td><td>{String(row.category_name||'Products')}</td><td>{money(row.price_minor,String(row.currency||'INR'))}</td><td>{String(row.inventory_quantity??0)}</td><td><em className={`badge ${row.active?'good':'bad'}`}><i/>{row.active?'Active':'Inactive'}</em></td><td>{date(row.created_at)}</td></>:view==='catalogs'?<><td><strong>{String(row.name||'—')}</strong><small>{String(row.description||'')}</small></td><td>{String(row.product_count||0)}</td><td><em className={`badge ${row.published?'good':''}`}><i/>{row.published?'Published':'Draft'}</em></td><td>{date(row.created_at)}</td></>:view==='customers'?<><td><strong>{String(row.name||'—')}</strong></td><td>{String(row.email||'—')}</td><td>{String(row.phone||'—')}</td><td>{String(row.order_count||0)}</td><td>{money(row.total_spent_minor,String(row.currency||'INR'))}</td><td>{date(row.created_at)}</td></>:<><td><strong>{String(row.external_reference||row.id)}</strong></td><td><em className="badge good"><i/>{String(row.status||'created')}</em></td><td>{money(row.total_minor,String(row.currency||'INR'))}</td><td>{String(row.delivery_order_id||'Pending')}</td><td>{date(row.created_at)}</td></>}</tr>)}{!loading&&!rows.length&&<tr><td colSpan={columns.length}><div className="storefront-empty"><ShoppingBag/><strong>No {view} yet</strong><span>Create the first record to start the live commerce flow.</span></div></td></tr>}</tbody></table></div></article>}

function SupportingView({view,store}:{view:View;store:Row}){const copy:Record<string,[string,string]>={networks:['Store networks','Share catalogs across connected stores and organizations.'],'food-trucks':['Mobile stores','Attach a live location and schedule to mobile storefronts.'],promotions:['Promotions','Create discount campaigns and customer notifications.'],settings:['Store settings','Configure identity, currency, fulfillment and notification defaults.'],launch:['Launch storefront','Connect the public catalog to your pharmacy commerce application.']};const [title,description]=copy[view]||['Storefront','Commerce configuration'];return <article className="storefront-support"><span><Store/></span><h2>{title}</h2><p>{description}</p>{view==='launch'?<div><code>DROO_PRODUCTS_PATH=/storefront/v1/products</code><code>DROO_STOREFRONT_ID={String(store.id||'str_…')}</code><a href="http://localhost:3001" target="_blank" rel="noreferrer" className="primary">Open pharmacy store <ExternalLink/></a></div>:<button className="secondary" disabled>Available in the next Storefront phase</button>}</article>}

function Editor({view,store,close,saved}:{view:View;store:Row;close:()=>void;saved:()=>void}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const data=new FormData(event.currentTarget);const body=view==='products'?{store_id:store.id,name:data.get('name'),sku:data.get('sku'),description:data.get('description'),category_name:data.get('category'),price_minor:Math.round(Number(data.get('price'))*100),currency:store.currency||'INR',inventory_quantity:Number(data.get('inventory')),active:true}:{store_id:store.id,name:data.get('name'),description:data.get('description'),published:data.get('published')==='on',product_ids:[]};try{const response=await fetchAuthenticated(endpoint[view]!,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`Create failed (${response.status})`);saved()}catch(value){setError(value instanceof Error?value.message:'Create failed')}finally{setBusy(false)}}return <div className="modal-backdrop"><form className="storefront-editor" onSubmit={submit}><header><div><h2>New {view==='products'?'product':'catalog'}</h2><p>Create a live Storefront resource.</p></div><button type="button" onClick={close}><X/></button></header><div><label><span>Name</span><input name="name" required autoFocus/></label>{view==='products'?<><label><span>SKU</span><input name="sku" required/></label><label><span>Category</span><input name="category" defaultValue="Medicine" required/></label><label><span>Price ({String(store.currency||'INR')})</span><input name="price" type="number" min="0" step="0.01" required/></label><label><span>Inventory</span><input name="inventory" type="number" min="0" defaultValue="10" required/></label></>:<label className="inline-check"><input name="published" type="checkbox"/> Publish immediately</label>}<label className="wide"><span>Description</span><textarea name="description" rows={4}/></label>{error&&<p className="editor-error">{error}</p>}</div><footer><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Create'}</button></footer></form></div>}
