'use client'

import { useMemo, useRef, useState, type ChangeEvent } from 'react'
import { ChevronLeft, ChevronRight, ChevronsUpDown, Copy, Download, MoreHorizontal, RefreshCw, Search, SlidersHorizontal, Upload } from 'lucide-react'
import { EmptyState } from '@/components/ui/empty-state'
import { PageHeader } from '@/components/ui/page-header'
import { StatusBadge } from '@/components/ui/status-badge'
import { fetchAuthenticated, useApiData } from '@/hooks/use-api-data'
import { modules } from '@/lib/dashboard-config'
import type { ApiRecord } from '@/types/dashboard'

type SortKey = 'name' | 'service_area_name' | 'parent_fleet_name' | 'zone' | 'manpower' | 'task' | 'status' | 'created_at'
const pageSize = 25
function text(value: unknown, fallback = '—') { return typeof value === 'string' && value.trim() ? value : fallback }
function dateTime(value: unknown) { const date = new Date(String(value || '')); return Number.isNaN(date.getTime()) ? '—' : date.toLocaleString() }
function SortHeader({ field, label, active, sort }: { field: SortKey; label: string; active: boolean; sort: (key: SortKey) => void }) { return <button className={active ? 'active' : ''} onClick={() => sort(field)}>{label}<ChevronsUpDown /></button> }

export function FleetRecordsPage() {
  const { rows, loading, error, refresh } = useApiData('Fleets', undefined, false)
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [sortKey, setSortKey] = useState<SortKey>('created_at'); const [direction, setDirection] = useState<'asc' | 'desc'>('desc'); const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [menu, setMenu] = useState(''); const [notice, setNotice] = useState(''); const [importing, setImporting] = useState(false); const importInput = useRef<HTMLInputElement>(null)
  const statuses = useMemo(() => Array.from(new Set(rows.map(row => text(row.status, '')).filter(Boolean))).sort(), [rows])
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return rows.filter(row => (!status || row.status === status) && (!query || [row.name, row.service_area_name, row.parent_fleet_name, row.zone, row.task, row.id].some(value => String(value || '').toLowerCase().includes(query)))).sort((a, b) => { const left = sortKey === 'manpower' ? Number(a[sortKey] || 0) : sortKey === 'created_at' ? new Date(String(a[sortKey] || '')).getTime() : text(a[sortKey], ''); const right = sortKey === 'manpower' ? Number(b[sortKey] || 0) : sortKey === 'created_at' ? new Date(String(b[sortKey] || '')).getTime() : text(b[sortKey], ''); const compared = typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right), undefined, { numeric: true, sensitivity: 'base' }); return direction === 'asc' ? compared : -compared }) }, [rows, search, status, sortKey, direction])
  const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const currentPage = Math.min(page, pageCount); const visible = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  const visibleIDs = visible.map(row => String(row.id)); const allSelected = Boolean(visibleIDs.length) && visibleIDs.every(id => selected.has(id))
  function sort(key: SortKey) { if (sortKey === key) setDirection(value => value === 'asc' ? 'desc' : 'asc'); else { setSortKey(key); setDirection('asc') } }
  function exportRows() { const keys = ['name', 'service_area_name', 'parent_fleet_name', 'zone', 'manpower', 'task', 'status', 'created_at']; const csv = [keys.join(','), ...filtered.map(row => keys.map(key => JSON.stringify(row[key] ?? '')).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'droo-fleets.csv'; link.click(); URL.revokeObjectURL(link.href) }
  async function importCSV(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setImporting(true); setNotice(''); try { const lines = (await file.text()).split(/\r?\n/).filter(Boolean); const headers = lines.shift()?.split(',').map(value => value.trim().toLowerCase().replaceAll(' ', '_')) || []; let created = 0; for (const line of lines) { const values = line.split(','); const fleet: Record<string, unknown> = Object.fromEntries(headers.map((key, index) => [key, values[index]?.trim() || null])); fleet.status ||= 'active'; const response = await fetchAuthenticated('/v1/admin/fleets', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fleet }) }); if (!response.ok) throw new Error(`Import stopped at row ${created + 2} (${response.status}).`); created += 1 } setNotice(`${created} fleet${created === 1 ? '' : 's'} imported.`); refresh() } catch (value) { setNotice(value instanceof Error ? value.message : 'Fleet import failed.') } finally { setImporting(false) } }
  function toggleVisible() { setSelected(current => { const next = new Set(current); visibleIDs.forEach(id => allSelected ? next.delete(id) : next.add(id)); return next }) }

  const headers: Array<[SortKey, string]> = [['name', 'Name'], ['service_area_name', 'Service area'], ['parent_fleet_name', 'Parent fleet'], ['zone', 'Zone'], ['manpower', 'Manpower'], ['task', 'Task'], ['status', 'Status'], ['created_at', 'Created']]
  return <><PageHeader config={modules.Fleets} onCreated={refresh} /><section className="vehicle-records fleet-records"><div className="vehicle-table-tools"><label><Search /><input value={search} onChange={event => { setSearch(event.target.value); setPage(1) }} placeholder="Search fleets" /></label><select value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option>{statuses.map(value => <option key={value}>{value}</option>)}</select><button title="Filter fleets"><SlidersHorizontal /></button><button onClick={refresh} aria-label="Refresh fleets"><RefreshCw /></button><button className="vehicle-import" onClick={() => importInput.current?.click()} disabled={importing}><Upload />{importing ? 'Importing…' : 'Import'}</button><input hidden ref={importInput} type="file" accept=".csv,text/csv" onChange={importCSV} /><button onClick={exportRows} disabled={!filtered.length}><Download />Export</button></div>
    {rows.length ? <div className="vehicle-table-wrap"><table className="vehicle-table fleet-table"><thead><tr><th><input type="checkbox" aria-label="Select visible fleets" checked={allSelected} onChange={toggleVisible} /></th>{headers.map(([key, label]) => <th key={key}><SortHeader field={key} label={label} active={sortKey === key} sort={sort} /></th>)}<th /></tr></thead><tbody>{visible.map((row: ApiRecord) => { const id = String(row.id); return <tr key={id}><td><input type="checkbox" aria-label={`Select ${text(row.name, id)}`} checked={selected.has(id)} onChange={() => setSelected(current => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next })} /></td><td><strong>{text(row.name, 'Unnamed fleet')}</strong></td><td>{text(row.service_area_name)}</td><td>{text(row.parent_fleet_name)}</td><td>{text(row.zone)}</td><td>{Number(row.manpower || 0) || '—'}</td><td>{text(row.task)}</td><td><StatusBadge value={text(row.status, 'active')} /></td><td>{dateTime(row.created_at)}</td><td className="vehicle-actions"><button onClick={() => setMenu(menu === id ? '' : id)} aria-label={`Actions for ${id}`}><MoreHorizontal /></button>{menu === id && <div><button onClick={() => { navigator.clipboard.writeText(id); setMenu(''); setNotice('Fleet ID copied.') }}><Copy />Copy fleet ID</button></div>}</td></tr> })}</tbody></table></div> : <EmptyState loading={loading} error={error} />}
    <footer className="vehicle-table-footer"><span>{selected.size ? `${selected.size} selected · ` : ''}{filtered.length ? `Showing ${(currentPage - 1) * pageSize + 1} to ${Math.min(currentPage * pageSize, filtered.length)} of ${filtered.length}` : 'No results'}</span><div><button disabled={currentPage <= 1} onClick={() => setPage(value => value - 1)}><ChevronLeft /></button><strong>{currentPage}</strong><button disabled={currentPage >= pageCount} onClick={() => setPage(value => value + 1)}><ChevronRight /></button></div></footer>{notice && <div className="vehicle-table-notice" role="status">{notice}</div>}</section></>
}
