'use client'

import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { BarChart3, BookOpen, Check, ChevronLeft, ChevronRight, Eye, Filter, MoreHorizontal, Play, Plus, RefreshCw, Search, Settings2, SlidersHorizontal, Trash2, X } from 'lucide-react'
import { deleteDashboardState, listDashboardState, putDashboardState } from '@/lib/dashboard-state'

type Report = { id:string; title:string; description:string; tags:string; source:string; fields:string[]; computed:{id:string;name:string;expression:string}[]; groupBy:string; sortBy:string; limit:number|null; conditions:{id:string;field:string;operator:string;value:string}[]; created:string }
const sources:Record<string,string[]>={Orders:['id','status','customer_name','service_type','price','created_at'],Drivers:['id','name','phone','status','vehicle_id','created_at'],Vehicles:['id','registration_number','type','status','assigned_driver'],Places:['id','name','city','country','type'],Contacts:['id','name','phone','email','type'],Vendors:['id','name','status','service_type','phone'], 'Fuel Reports':['id','vehicle_id','litres','amount','distance','created_at']}
const LOCAL_REPORTS_KEY='droo.analytics.reports.v1'
const emptyReport=():Report=>({id:'',title:'',description:'',tags:'',source:'',fields:[],computed:[],groupBy:'',sortBy:'',limit:50,conditions:[],created:''})
const blankFilters=()=>({title:'',id:''})
function localReports(){try{return JSON.parse(localStorage.getItem(LOCAL_REPORTS_KEY)||'[]') as Report[]}catch{return []}}
function saveLocalReports(reports:Report[]){localStorage.setItem(LOCAL_REPORTS_KEY,JSON.stringify(reports))}

export function ReportsPage(){
  const params=useSearchParams()
  const [rows,setRows]=useState<Report[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[filters,setFilters]=useState(blankFilters),[draftFilters,setDraftFilters]=useState(blankFilters)
  const [filtersOpen,setFiltersOpen]=useState(false),[columnsOpen,setColumnsOpen]=useState(false),[visibleColumns,setVisibleColumns]=useState({Title:true,ID:true}),[editor,setEditor]=useState<Report|null>(()=>params.get('new')==='true'?emptyReport():null)
  const [tab,setTab]=useState<'configuration'|'preview'>('configuration'),[fieldSearch,setFieldSearch]=useState(''),[notice,setNotice]=useState(''),[guideOpen,setGuideOpen]=useState(false),[menu,setMenu]=useState<string|null>(null)
  async function load(){try{const stored=await listDashboardState<Report>('analytics-reports');setRows(stored.map(entry=>entry.value));setNotice('')}catch{if(process.env.NEXT_PUBLIC_ENABLE_DEV_LOGIN==='true'){setRows(localReports());setNotice('')}else setNotice('Unable to load reports.')}finally{setLoading(false)}}
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[])
  const visible=useMemo(()=>rows.filter(row=>`${row.title} ${row.id}`.toLowerCase().includes(search.toLowerCase())&&row.title.toLowerCase().includes(filters.title.toLowerCase())&&row.id.toLowerCase().includes(filters.id.toLowerCase())),[rows,search,filters])
  function setEditorUrl(open:boolean){const url=new URL(window.location.href);if(open)url.searchParams.set('new','true');else url.searchParams.delete('new');window.history.replaceState({},'',url)}
  function openEditor(report=emptyReport()){setEditor(report);setTab('configuration');setFieldSearch('');setEditorUrl(true)}
  function closeEditor(){setEditor(null);setEditorUrl(false)}
  async function save(){if(!editor?.title.trim()){setNotice('Report title is required.');return}if(!editor.source){setNotice('Select a data source.');return}const id=editor.id||`rpt_${crypto.randomUUID().replaceAll('-','').slice(0,10)}`;const value={...editor,id,created:editor.created||new Date().toISOString()};try{await putDashboardState('analytics-reports',id,value)}catch(error){if(process.env.NEXT_PUBLIC_ENABLE_DEV_LOGIN!=='true'){setNotice(error instanceof Error?error.message:'Unable to save report.');return}const next=[value,...localReports().filter(item=>item.id!==id)];saveLocalReports(next)}setRows(items=>[value,...items.filter(item=>item.id!==id)]);closeEditor();setNotice(editor.id?'Report updated.':'Report created.')}
  async function remove(report:Report){try{await deleteDashboardState('analytics-reports',report.id)}catch(error){if(process.env.NEXT_PUBLIC_ENABLE_DEV_LOGIN!=='true'){setNotice(error instanceof Error?error.message:'Unable to delete report.');return}saveLocalReports(localReports().filter(item=>item.id!==report.id))}setRows(items=>items.filter(item=>item.id!==report.id));setMenu(null);setNotice('Report deleted.')}
  function update(changes:Partial<Report>){setEditor(current=>current?{...current,...changes}:current)}
  return <div className="maintenance-list-page reports-page"><header className="maintenance-list-header"><h2>Reports</h2><div className="maintenance-list-search"><Search/><input aria-label="Search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search Reports"/></div><div className="maintenance-list-actions">
    <button aria-label="Filter reports" className={filtersOpen?'active':''} onClick={()=>{setDraftFilters(filters);setFiltersOpen(value=>!value);setColumnsOpen(false)}}><Filter/></button><button aria-label="Customize columns" className={columnsOpen?'active':''} onClick={()=>{setColumnsOpen(value=>!value);setFiltersOpen(false)}}><SlidersHorizontal/></button><button aria-label="Refresh" onClick={()=>{setLoading(true);void load()}}><RefreshCw className={loading?'spin':''}/></button><button className="new-schedule-action" onClick={()=>openEditor()}><Plus/>New</button>
    {filtersOpen&&<div className="maintenance-filter-panel reports-filter"><header>Filters</header><div className="maintenance-filter-grid">{Object.entries(draftFilters).map(([key,value])=><label key={key}><strong>{key==='id'?'ID':'Title'}</strong><span><input value={value} onChange={event=>setDraftFilters(current=>({...current,[key]:event.target.value}))} placeholder={key==='id'?'ID':'Title'}/>{value&&<button onClick={()=>setDraftFilters(current=>({...current,[key]:''}))}><X/></button>}</span></label>)}</div><footer><button onClick={()=>{const clear=blankFilters();setDraftFilters(clear);setFilters(clear);setFiltersOpen(false)}}><Trash2/>Clear</button><button className="apply" onClick={()=>{setFilters(draftFilters);setFiltersOpen(false)}}><Check/>Apply</button></footer></div>}
    {columnsOpen&&<div className="maintenance-columns-menu"><strong>Customize columns</strong>{(['Title','ID'] as const).map(column=><label key={column}><input type="checkbox" checked={visibleColumns[column]} onChange={event=>setVisibleColumns(current=>({...current,[column]:event.target.checked}))}/>{column}</label>)}<button className="columns-done" onClick={()=>setColumnsOpen(false)}>Done</button></div>}
  </div></header>{notice&&<div className="maintenance-list-notice">{notice}<button aria-label="Dismiss message" onClick={()=>setNotice('')}><X/></button></div>}
  <section className="maintenance-table-panel"><div className="table-wrap"><table className="maintenance-schedules-table reports-table"><thead><tr><th><input type="checkbox" aria-label="Select all reports"/></th>{visibleColumns.Title&&<th>Title<span>↕</span></th>}{visibleColumns.ID&&<th>ID<span>↕</span></th>}<th/></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td><input type="checkbox" aria-label={`Select ${row.title}`}/></td>{visibleColumns.Title&&<td><button className="schedule-id" onClick={()=>openEditor(row)}>{row.title}</button></td>}{visibleColumns.ID&&<td>{row.id}</td>}<td className="schedule-row-actions"><button aria-label={`Actions for ${row.title}`} onClick={()=>setMenu(menu===row.id?null:row.id)}><MoreHorizontal/></button>{menu===row.id&&<div role="menu"><strong>Report Actions</strong><button onClick={()=>openEditor(row)}><Eye/>View / Edit</button><button className="danger" onClick={()=>void remove(row)}><Trash2/>Delete</button></div>}</td></tr>)}</tbody></table></div>{!loading&&!visible.length&&<div className="reports-empty"><span><BarChart3/></span><h3>No reports yet</h3><p>Create a Fleet-Ops report to start tracking operational trends, utilization, and performance over time.</p><div><button onClick={()=>void load()}><RefreshCw/>Refresh</button><button className="primary" onClick={()=>openEditor()}><Plus/>New report</button></div><button className="guide" onClick={()=>setGuideOpen(true)}><BookOpen/>Reports guide</button></div>}<footer><p>Showing <b>{visible.length?1:0}</b> to <b>{visible.length||1}</b> of <b>{visible.length}</b> results</p><div><button disabled><ChevronLeft/></button><button className="active">1</button><button disabled><ChevronRight/></button></div></footer></section>
  {editor&&<ReportBuilder report={editor} tab={tab} fieldSearch={fieldSearch} onSearch={setFieldSearch} onTab={setTab} onUpdate={update} onSave={()=>void save()} onClose={closeEditor}/>} {guideOpen&&<ReportsGuide onClose={()=>setGuideOpen(false)}/>}</div>
}

function ReportBuilder({report,tab,fieldSearch,onSearch,onTab,onUpdate,onSave,onClose}:{report:Report;tab:'configuration'|'preview';fieldSearch:string;onSearch:(value:string)=>void;onTab:(value:'configuration'|'preview')=>void;onUpdate:(changes:Partial<Report>)=>void;onSave:()=>void;onClose:()=>void}){
  const fields=(sources[report.source]||[]).filter(field=>field.includes(fieldSearch.toLowerCase()))
  const toggleField=(field:string)=>onUpdate({fields:report.fields.includes(field)?report.fields.filter(item=>item!==field):[...report.fields,field]})
  return <div className="reports-builder-backdrop"><section className="reports-builder" role="dialog" aria-modal="true" aria-label={report.id?'Edit report':'Create new report'}><header><div><h2>{report.id?'Edit report':'Create new report'}</h2><p>{report.id?'Update this report configuration.':'Create a reusable Fleet-Ops report.'}</p></div><button aria-label="Close report builder" onClick={onClose}><X/></button></header><div className="reports-builder-body"><details open><summary>Report Details</summary><div className="report-details"><label>Title<input aria-label="Title" value={report.title} onChange={event=>onUpdate({title:event.target.value})} placeholder="Title"/></label><label>Description<textarea aria-label="Description" value={report.description} onChange={event=>onUpdate({description:event.target.value})} placeholder="Description"/></label><label>Tags<input aria-label="Add tags to the report" value={report.tags} onChange={event=>onUpdate({tags:event.target.value})} placeholder="Add tags to the report"/></label></div></details><div className="report-builder-tabs" role="tablist"><button role="tab" className={tab==='configuration'?'active':''} onClick={()=>onTab('configuration')}><Filter/>Configuration</button><button role="tab" className={tab==='preview'?'active':''} onClick={()=>onTab('preview')}><Settings2/>Preview</button><button className="execute" onClick={()=>onTab('preview')}><Play/>Execute</button></div>{tab==='configuration'?<div className="report-config" role="tabpanel" aria-label="Configuration">
    <ConfigSection title="Data Source" note={report.source||'No source selected'}><select aria-label="Data Source" value={report.source} onChange={event=>onUpdate({source:event.target.value,fields:[],groupBy:'',sortBy:''})}><option value="">Select data source...</option>{Object.keys(sources).map(source=><option key={source}>{source}</option>)}</select></ConfigSection>
    <ConfigSection title="Select fields" note={report.fields.length?`${report.fields.length} selected`:'None selected'}><input aria-label="Search for a column" value={fieldSearch} onChange={event=>onSearch(event.target.value)} placeholder="Search for a column"/>{report.source?<div className="report-field-list">{fields.map(field=><label key={field}><input type="checkbox" checked={report.fields.includes(field)} onChange={()=>toggleField(field)}/>{field.replaceAll('_',' ')}</label>)}</div>:<EmptyConfig title="Select a data source" text="Choose a table to see available fields"/>}</ConfigSection>
    <ConfigSection title="Computed Columns" action={<button onClick={()=>onUpdate({computed:[...report.computed,{id:crypto.randomUUID(),name:'',expression:''}]})}><Plus/>Add Computed Column</button>}>{report.computed.length?<div className="computed-list">{report.computed.map(item=><div key={item.id}><input aria-label="Computed column name" placeholder="Column name" value={item.name} onChange={event=>onUpdate({computed:report.computed.map(row=>row.id===item.id?{...row,name:event.target.value}:row)})}/><input aria-label="SQL expression" placeholder="SQL expression" value={item.expression} onChange={event=>onUpdate({computed:report.computed.map(row=>row.id===item.id?{...row,expression:event.target.value}:row)})}/><button aria-label="Remove computed column" onClick={()=>onUpdate({computed:report.computed.filter(row=>row.id!==item.id)})}><Trash2/></button></div>)}</div>:<EmptyConfig title="No computed columns defined yet" text="Computed columns allow you to create calculated fields using SQL expressions"/>}</ConfigSection>
    <div className="report-config-pair"><ConfigSection title="Group By" note={report.groupBy||'No grouping'}><select disabled={!report.fields.length} value={report.groupBy} onChange={event=>onUpdate({groupBy:event.target.value})}><option value="">No grouping</option>{report.fields.map(field=><option key={field}>{field}</option>)}</select></ConfigSection><ConfigSection title="Sort By" note={report.sortBy||'No sorting'}><select disabled={!report.fields.length} value={report.sortBy} onChange={event=>onUpdate({sortBy:event.target.value})}><option value="">No sorting</option>{report.fields.map(field=><option key={field}>{field}</option>)}</select></ConfigSection></div>
    <ConfigSection title="Limit Results" note={report.limit===null?'No limit':`Max ${report.limit} rows`}><label className="limit-input">Maximum rows:<input type="number" min="1" value={report.limit??''} onChange={event=>onUpdate({limit:event.target.value?Number(event.target.value):null})}/></label><div className="quick-limits">{[10,25,50,100,250,500,1000,5000].map(limit=><button key={limit} onClick={()=>onUpdate({limit})}>{limit>=1000?`${limit/1000}K`:limit}</button>)}<button onClick={()=>onUpdate({limit:null})}>Remove Limit</button></div></ConfigSection>
    <ConfigSection title="Joins" note="No joins"><EmptyConfig title="No relationships available" text="This table has no defined relationships to join with other tables"/></ConfigSection>
    <ConfigSection title="Conditions" note={report.conditions.length?`${report.conditions.length} conditions`:'No conditions'} action={<button disabled={!report.fields.length} onClick={()=>onUpdate({conditions:[...report.conditions,{id:crypto.randomUUID(),field:report.fields[0],operator:'equals',value:''}]})}><Plus/>Add Condition</button>}>{report.conditions.length?<div className="conditions-list">{report.conditions.map(condition=><div key={condition.id}><select value={condition.field} onChange={event=>onUpdate({conditions:report.conditions.map(row=>row.id===condition.id?{...row,field:event.target.value}:row)})}>{report.fields.map(field=><option key={field}>{field}</option>)}</select><select value={condition.operator} onChange={event=>onUpdate({conditions:report.conditions.map(row=>row.id===condition.id?{...row,operator:event.target.value}:row)})}><option value="equals">Equals</option><option value="contains">Contains</option><option value="greater">Greater than</option></select><input value={condition.value} onChange={event=>onUpdate({conditions:report.conditions.map(row=>row.id===condition.id?{...row,value:event.target.value}:row)})} placeholder="Value"/><button onClick={()=>onUpdate({conditions:report.conditions.filter(row=>row.id!==condition.id)})}><Trash2/></button></div>)}</div>:<EmptyConfig title={report.fields.length?'No conditions':'Select fields first'} text={report.fields.length?'Add a condition to filter report rows':'Choose columns to enable filtering'}/>}</ConfigSection>
  </div>:<ReportPreview report={report}/>}</div><footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={onSave}><Check/>{report.id?'Save Report':'Create Report'}</button></footer></section></div>
}

function ConfigSection({title,note,action,children}:{title:string;note?:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="config-section"><header><strong>{title}</strong>{note&&<span>{note}</span>}{action}</header><div>{children}</div></section>}
function EmptyConfig({title,text}:{title:string;text:string}){return <div className="empty-config"><Settings2/><strong>{title}</strong><span>{text}</span></div>}
function ReportPreview({report}:{report:Report}){const columns=[...report.fields,...report.computed.map(item=>item.name).filter(Boolean)];return <div className="report-preview" role="tabpanel" aria-label="Preview"><h3>Report Preview</h3><p>{report.source?`Previewing ${report.source} with ${columns.length} columns.`:'Select a data source and fields to preview this report.'}</p>{columns.length?<table><thead><tr>{columns.map(column=><th key={column}>{column.replaceAll('_',' ')}</th>)}</tr></thead><tbody><tr>{columns.map(column=><td key={column}>—</td>)}</tr></tbody></table>:<EmptyConfig title="Nothing to preview" text="Configure the report, then click Execute"/>}</div>}
function ReportsGuide({onClose}:{onClose:()=>void}){return <div className="reports-guide-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section role="dialog" aria-modal="true" aria-label="Reports guide"><header><h2>Reports guide</h2><button aria-label="Close Reports guide" onClick={onClose}><X/></button></header><article><BookOpen/><h1>Fleet-Ops Reports</h1><p>Create reusable operational reports from Orders, Drivers, Vehicles, Places, Contacts, Vendors, and Fuel Reports.</p><h2>Build a report</h2><ol><li>Enter a title and optional description and tags.</li><li>Select the data source.</li><li>Choose the fields to include.</li><li>Add computed columns, grouping, sorting, limits, and conditions.</li><li>Execute a preview and create the report.</li></ol></article></section></div>}
